# coding: utf-8

# flake8: noqa
"""
    Betaface API 2.0

    Betaface face recognition API.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.cropped_face import CroppedFace
from swagger_client.models.error import Error
from swagger_client.models.face import Face
from swagger_client.models.match import Match
from swagger_client.models.media import Media
from swagger_client.models.media_upload import MediaUpload
from swagger_client.models.media_upload_file import MediaUploadFile
from swagger_client.models.media_upload_response import MediaUploadResponse
from swagger_client.models.new_face import NewFace
from swagger_client.models.person import Person
from swagger_client.models.point import Point
from swagger_client.models.recognize import Recognize
from swagger_client.models.recognize_request import RecognizeRequest
from swagger_client.models.recognize_result import RecognizeResult
from swagger_client.models.set_person import SetPerson
from swagger_client.models.tag import Tag
from swagger_client.models.tag_media import TagMedia
from swagger_client.models.transform import Transform
from swagger_client.models.transform_request import TransformRequest
from swagger_client.models.usage import Usage
from swagger_client.models.usage_daily import UsageDaily
