# coding: utf-8

"""
    Betaface API 2.0

    Betaface face recognition API.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.face import Face  # noqa: F401,E501


class CroppedFace(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'image_base64': 'str',
        'face': 'Face'
    }

    attribute_map = {
        'image_base64': 'image_base64',
        'face': 'face'
    }

    def __init__(self, image_base64=None, face=None):  # noqa: E501
        """CroppedFace - a model defined in Swagger"""  # noqa: E501

        self._image_base64 = None
        self._face = None
        self.discriminator = None

        if image_base64 is not None:
            self.image_base64 = image_base64
        if face is not None:
            self.face = face

    @property
    def image_base64(self):
        """Gets the image_base64 of this CroppedFace.  # noqa: E501

        base64 encoded cropped face image file (jpg or png).  # noqa: E501

        :return: The image_base64 of this CroppedFace.  # noqa: E501
        :rtype: str
        """
        return self._image_base64

    @image_base64.setter
    def image_base64(self, image_base64):
        """Sets the image_base64 of this CroppedFace.

        base64 encoded cropped face image file (jpg or png).  # noqa: E501

        :param image_base64: The image_base64 of this CroppedFace.  # noqa: E501
        :type: str
        """

        self._image_base64 = image_base64

    @property
    def face(self):
        """Gets the face of this CroppedFace.  # noqa: E501

        face information with pixel related properties in cropped image pixel space.  # noqa: E501

        :return: The face of this CroppedFace.  # noqa: E501
        :rtype: Face
        """
        return self._face

    @face.setter
    def face(self, face):
        """Sets the face of this CroppedFace.

        face information with pixel related properties in cropped image pixel space.  # noqa: E501

        :param face: The face of this CroppedFace.  # noqa: E501
        :type: Face
        """

        self._face = face

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CroppedFace, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CroppedFace):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
