# coding: utf-8

"""
    Betaface API 2.0

    Betaface face recognition API.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Match(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'face_uuid': 'str',
        'confidence': 'float',
        'is_match': 'bool',
        'person_id': 'str'
    }

    attribute_map = {
        'face_uuid': 'face_uuid',
        'confidence': 'confidence',
        'is_match': 'is_match',
        'person_id': 'person_id'
    }

    def __init__(self, face_uuid=None, confidence=None, is_match=None, person_id=None):  # noqa: E501
        """Match - a model defined in Swagger"""  # noqa: E501

        self._face_uuid = None
        self._confidence = None
        self._is_match = None
        self._person_id = None
        self.discriminator = None

        if face_uuid is not None:
            self.face_uuid = face_uuid
        if confidence is not None:
            self.confidence = confidence
        if is_match is not None:
            self.is_match = is_match
        if person_id is not None:
            self.person_id = person_id

    @property
    def face_uuid(self):
        """Gets the face_uuid of this Match.  # noqa: E501

        matching face unique identifier.  # noqa: E501

        :return: The face_uuid of this Match.  # noqa: E501
        :rtype: str
        """
        return self._face_uuid

    @face_uuid.setter
    def face_uuid(self, face_uuid):
        """Sets the face_uuid of this Match.

        matching face unique identifier.  # noqa: E501

        :param face_uuid: The face_uuid of this Match.  # noqa: E501
        :type: str
        """

        self._face_uuid = face_uuid

    @property
    def confidence(self):
        """Gets the confidence of this Match.  # noqa: E501

        match confidence (recognition score).  # noqa: E501

        :return: The confidence of this Match.  # noqa: E501
        :rtype: float
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence):
        """Sets the confidence of this Match.

        match confidence (recognition score).  # noqa: E501

        :param confidence: The confidence of this Match.  # noqa: E501
        :type: float
        """

        self._confidence = confidence

    @property
    def is_match(self):
        """Gets the is_match of this Match.  # noqa: E501

        decision is it same person or not based on match confidence with threshold measured on small and medium sized test collections.  # noqa: E501

        :return: The is_match of this Match.  # noqa: E501
        :rtype: bool
        """
        return self._is_match

    @is_match.setter
    def is_match(self, is_match):
        """Sets the is_match of this Match.

        decision is it same person or not based on match confidence with threshold measured on small and medium sized test collections.  # noqa: E501

        :param is_match: The is_match of this Match.  # noqa: E501
        :type: bool
        """

        self._is_match = is_match

    @property
    def person_id(self):
        """Gets the person_id of this Match.  # noqa: E501

        person id assigned to matching face, if any.  # noqa: E501

        :return: The person_id of this Match.  # noqa: E501
        :rtype: str
        """
        return self._person_id

    @person_id.setter
    def person_id(self, person_id):
        """Sets the person_id of this Match.

        person id assigned to matching face, if any.  # noqa: E501

        :param person_id: The person_id of this Match.  # noqa: E501
        :type: str
        """

        self._person_id = person_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Match, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Match):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
