# coding: utf-8

"""
    Betaface API 2.0

    Betaface face recognition API.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.media import Media  # noqa: F401,E501
from swagger_client.models.recognize import Recognize  # noqa: F401,E501


class MediaUploadResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'media': 'Media',
        'recognize': 'Recognize'
    }

    attribute_map = {
        'media': 'media',
        'recognize': 'recognize'
    }

    def __init__(self, media=None, recognize=None):  # noqa: E501
        """MediaUploadResponse - a model defined in Swagger"""  # noqa: E501

        self._media = None
        self._recognize = None
        self.discriminator = None

        if media is not None:
            self.media = media
        if recognize is not None:
            self.recognize = recognize

    @property
    def media(self):
        """Gets the media of this MediaUploadResponse.  # noqa: E501

        media information.  # noqa: E501

        :return: The media of this MediaUploadResponse.  # noqa: E501
        :rtype: Media
        """
        return self._media

    @media.setter
    def media(self, media):
        """Sets the media of this MediaUploadResponse.

        media information.  # noqa: E501

        :param media: The media of this MediaUploadResponse.  # noqa: E501
        :type: Media
        """

        self._media = media

    @property
    def recognize(self):
        """Gets the recognize of this MediaUploadResponse.  # noqa: E501

        recognition results.  # noqa: E501

        :return: The recognize of this MediaUploadResponse.  # noqa: E501
        :rtype: Recognize
        """
        return self._recognize

    @recognize.setter
    def recognize(self, recognize):
        """Sets the recognize of this MediaUploadResponse.

        recognition results.  # noqa: E501

        :param recognize: The recognize of this MediaUploadResponse.  # noqa: E501
        :type: Recognize
        """

        self._recognize = recognize

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MediaUploadResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MediaUploadResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
