# coding: utf-8

"""
    Betaface API 2.0

    Betaface face recognition API.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.usage_daily import UsageDaily  # noqa: F401,E501


class Usage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'usage_daily': 'list[UsageDaily]'
    }

    attribute_map = {
        'usage_daily': 'usage_daily'
    }

    def __init__(self, usage_daily=None):  # noqa: E501
        """Usage - a model defined in Swagger"""  # noqa: E501

        self._usage_daily = None
        self.discriminator = None

        if usage_daily is not None:
            self.usage_daily = usage_daily

    @property
    def usage_daily(self):
        """Gets the usage_daily of this Usage.  # noqa: E501

        list of usage statistics by day  # noqa: E501

        :return: The usage_daily of this Usage.  # noqa: E501
        :rtype: list[UsageDaily]
        """
        return self._usage_daily

    @usage_daily.setter
    def usage_daily(self, usage_daily):
        """Sets the usage_daily of this Usage.

        list of usage statistics by day  # noqa: E501

        :param usage_daily: The usage_daily of this Usage.  # noqa: E501
        :type: list[UsageDaily]
        """

        self._usage_daily = usage_daily

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Usage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Usage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
