# coding: utf-8

"""
    Betaface API 2.0

    Betaface face recognition API.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.person_api import PersonApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPersonApi(unittest.TestCase):
    """PersonApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.person_api.PersonApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v2_person_get(self):
        """Test case for v2_person_get

        lists all persons and their faces identifiers sorted by namespace and person name alphabetically. (Administrative endpoint - API secret required)  # noqa: E501
        """
        pass

    def test_v2_person_post(self):
        """Test case for v2_person_post

        sets or overwrites person id for each specified face.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
