# coding: utf-8

"""
    Betaface API 2.0

    Betaface face recognition API.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.recognize import Recognize  # noqa: E501
from swagger_client.rest import ApiException


class TestRecognize(unittest.TestCase):
    """Recognize unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecognize(self):
        """Test Recognize"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.recognize.Recognize()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
