# coding: utf-8

"""
    Betaface API 2.0

    Betaface face recognition API.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.transform_request import TransformRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestTransformRequest(unittest.TestCase):
    """TransformRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransformRequest(self):
        """Test TransformRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.transform_request.TransformRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
