# coding: utf-8

"""
    Betaface API 2.0

    Betaface face recognition API.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transform_api import TransformApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransformApi(unittest.TestCase):
    """TransformApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.transform_api.TransformApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v2_transform_get(self):
        """Test case for v2_transform_get

        gets a faces transform result.  # noqa: E501
        """
        pass

    def test_v2_transform_post(self):
        """Test case for v2_transform_post

        initiate transform for one or more faces  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
