# coding: utf-8

"""
    Betaface API 2.0

    Betaface face recognition API.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.recognize_api import RecognizeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRecognizeApi(unittest.TestCase):
    """RecognizeApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.recognize_api.RecognizeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v2_recognize_get(self):
        """Test case for v2_recognize_get

        gets a faces recognition result.  # noqa: E501
        """
        pass

    def test_v2_recognize_post(self):
        """Test case for v2_recognize_post

        initiate recognition for one or more faces  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
